name: Update website submodule

on:
  push:
    branches: [main]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          persist-credentials: false
      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Clone website repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/samarth261/samarth261.github.io.git website
      - name: Update ai-mad-lad
        run: |
          cd website
          remote=https:\\/\\/x-access-token:${{ secrets.GH_PAT }}@github.com\\/
          remote+=samarth261\\/ai-mad-lad.git
          sed -i "s/git@github.com:samarth261\/ai-mad-lad.git/$remote/g" .gitmodules > .gitmodules
          
          git submodule update --init --recursive
          git add ai-mad-lad
          git commit -m "Update ai-mad-lad" || echo "No changes to commit"
      - name: Push changes
        run: |
          cd website
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/samarth261/samarth261.github.io.git
          git push origin HEAD:main
